export interface ContaDRE {
  codigo: string;
  nome: string;
  nivel: number;
  tipo: 'grupo' | 'conta';
  filhos?: ContaDRE[];
}

export const PLANO_CONTAS_DRE: ContaDRE[] = [
  {
    codigo: '01',
    nome: 'RECEITA BRUTA',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      {
        codigo: '01.01',
        nome: 'RECEITA VENDA MERCADORIAS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '01.01.01', nome: 'VENDA A VISTA', nivel: 3, tipo: 'conta' },
          { codigo: '01.01.02', nome: 'VENDA A PRAZO', nivel: 3, tipo: 'conta' },
          { codigo: '01.01.03', nome: 'TRANSFERENCIA LOJAS', nivel: 3, tipo: 'conta' },
        ],
      },
      { codigo: '01.02', nome: 'RECEITA FRETE VENDA', nivel: 2, tipo: 'conta' },
    ],
  },
  {
    codigo: '02',
    nome: 'DEDUCOES DA RECEITA BRUTA',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      {
        codigo: '02.01',
        nome: 'DEDUCOES E ABATIMENTOS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '02.01.01', nome: 'DESCONTOS CONCEDIDOS PRODUTOS EM LINHA', nivel: 3, tipo: 'conta' },
          { codigo: '02.01.02', nome: 'DESCONTOS CONCEDIDOS PRODUTOS FORA DE LINHA', nivel: 3, tipo: 'conta' },
          { codigo: '02.01.03', nome: 'DEVOLUCOES DE VENDAS COMERCIAIS', nivel: 3, tipo: 'conta' },
          { codigo: '02.01.04', nome: 'DEV TRANSF LOJAS', nivel: 3, tipo: 'conta' },
          { codigo: '02.01.05', nome: 'DEVOLUCOES DE VENDAS QUALIDADE', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '02.02',
        nome: 'IMPOSTOS SOBRE VENDAS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '02.02.01', nome: 'ICMS SOBRE VENDAS', nivel: 3, tipo: 'conta' },
          { codigo: '02.02.02', nome: 'PIS SOBRE RECEITA', nivel: 3, tipo: 'conta' },
          { codigo: '02.02.03', nome: 'COFINS SOBRE RECEITA', nivel: 3, tipo: 'conta' },
          { codigo: '02.02.04', nome: 'IRRF REPRESENTANTES 8045', nivel: 3, tipo: 'conta' },
          { codigo: '02.02.05', nome: 'DIFAL GNRE', nivel: 3, tipo: 'conta' },
          { codigo: '02.02.06', nome: 'SIMPLES NACIONAL', nivel: 3, tipo: 'conta' },
          { codigo: '02.02.07', nome: 'ICMS DIF ALIQUOTA', nivel: 3, tipo: 'conta' },
        ],
      },
    ],
  },
  {
    codigo: '04',
    nome: 'CUSTOS VARIAVEIS',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      {
        codigo: '04.01',
        nome: 'CUSTOS COM IMPOSTOS DIRETOS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '04.01.01', nome: 'ICMS ANTECIPADO', nivel: 3, tipo: 'conta' },
          { codigo: '04.01.02', nome: 'ICMS SUBSTITUICAO', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '04.02',
        nome: 'CUSTOS COM PRODUTOS VENDIDOS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          {
            codigo: '04.02.01',
            nome: 'CUSTO PRODUTO VENDIDOS',
            nivel: 3,
            tipo: 'grupo',
            filhos: [
              { codigo: '04.02.01.01', nome: 'MATERIA PRIMA', nivel: 4, tipo: 'conta' },
              { codigo: '04.02.01.02', nome: 'COSTURA', nivel: 4, tipo: 'conta' },
              { codigo: '04.02.01.03', nome: 'CORTE', nivel: 4, tipo: 'conta' },
              { codigo: '04.02.01.04', nome: 'ENERGIA ELETRICA', nivel: 4, tipo: 'conta' },
              { codigo: '04.02.01.05', nome: 'DEPRECIACAO INDUSTRIAL', nivel: 4, tipo: 'conta' },
            ],
          },
          { codigo: '04.02.02', nome: 'CUSTO MERCADORIAS VENDIDAS', nivel: 3, tipo: 'conta' },
        ],
      },
    ],
  },
  {
    codigo: '06',
    nome: 'CUSTOS FIXOS',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      {
        codigo: '06.01',
        nome: 'GASTOS GERAIS DE FABRICACAO',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '06.01.01', nome: 'AGUA E ESGOTO PROD', nivel: 3, tipo: 'conta' },
          { codigo: '06.01.02', nome: 'CONSULTORIAS E ASSESSORIAS INDUSTRIAIS', nivel: 3, tipo: 'conta' },
          { codigo: '06.01.03', nome: 'MANUTENCOES DE INSTALACOES INDUSTRIAIS', nivel: 3, tipo: 'conta' },
          { codigo: '06.01.04', nome: 'MANUTENCOES DE MAQUINAS INDUSTRIAIS', nivel: 3, tipo: 'conta' },
          { codigo: '06.01.05', nome: 'MATERIAIS AUXILIARES DE PRODUCAO', nivel: 3, tipo: 'conta' },
          { codigo: '06.01.06', nome: 'SERVICOS DE COLETA DE RESIDUOS PROD', nivel: 3, tipo: 'conta' },
        ],
      },
    ],
  },
  {
    codigo: '12',
    nome: 'DESPESAS COM DEPRECIACAO',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      {
        codigo: '12.01',
        nome: 'DEPRECIACAO DO IMOBILIZADO',
        nivel: 2,
        tipo: 'grupo',
        filhos: [],
      },
    ],
  },
  {
    codigo: '08',
    nome: 'DESPESAS OPERACIONAIS',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      {
        codigo: '08.10',
        nome: 'DESPESAS COM VENDAS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.10.01', nome: 'FRETES VENDAS', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.02', nome: 'COMISSAO GERENTE', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.03', nome: 'COMISSAO REPRESENTANTE', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.04', nome: 'PREMIACOES COMERCIAIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.05', nome: 'TAXAS CARTAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.06', nome: 'RESCISAO REPRESENTANTES', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.07', nome: 'COMISSAO VENDEDOR', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.08', nome: 'COMISSAO CORRETOR', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.09', nome: 'COMISSAO COORDENADOR', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.10', nome: 'COMISSAO MARKET PLACE', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.11', nome: 'PREMIACOES COMERCIAIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.10.12', nome: 'COMISSAO SUPERVISOR', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '08.01',
        nome: 'DESPESAS COM OCUPACAO',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.01.01', nome: 'CONDOMINIO - CO', nivel: 3, tipo: 'conta' },
          { codigo: '08.01.02', nome: 'ALUGUEL MINIMO - CO', nivel: 3, tipo: 'conta' },
          { codigo: '08.01.03', nome: 'FUNDO DE PROMOCAO - CO', nivel: 3, tipo: 'conta' },
          { codigo: '08.01.04', nome: 'ENERGIA - CO', nivel: 3, tipo: 'conta' },
          { codigo: '08.01.05', nome: 'AR CONDICIONADO - CO', nivel: 3, tipo: 'conta' },
          { codigo: '08.01.06', nome: 'IPTU - CO', nivel: 3, tipo: 'conta' },
          { codigo: '08.01.07', nome: 'TAXAS E EMOLUMENTO - CO', nivel: 3, tipo: 'conta' },
          { codigo: '08.01.08', nome: 'IRRF SOBRE ALUGUEL 3208 - CO', nivel: 3, tipo: 'conta' },
          { codigo: '08.01.09', nome: 'DESCONTOS FINANCEIROS OBTIDOS - CO', nivel: 3, tipo: 'conta' },
          { codigo: '08.01.10', nome: 'OUTRAS DESPESAS DE OCUPACAO', nivel: 3, tipo: 'conta' },
          ],
        },
      {
        codigo: '08.02',
        nome: 'DESPESAS ADMINISTRATIVAS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.02.01', nome: 'ASSESSORIA JURIDICA', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.02', nome: 'ASSESSORIA CONTABIL', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.03', nome: 'MONIT/SEGURANCA', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.04', nome: 'ASSOCIACAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.05', nome: 'MATERIAL DE LIMPEZA', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.06', nome: 'MAT DE CONSUMO', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.07', nome: 'AGUA MINERAL', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.08', nome: 'ENERGIA', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.09', nome: 'TELEFONIA FIXA', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.10', nome: 'CAGECE', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.11', nome: 'SERV DEDETIZACAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.12', nome: 'DESPESA DE CARTORIO', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.13', nome: 'CONSULTORIA', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.14', nome: 'SEGUROS DE IMOVEIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.15', nome: 'ALUGUEL MAQUINETA', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.16', nome: 'TELEFONIA MOVEL', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.17', nome: 'SERV INTERNET', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.18', nome: 'CORREIOS E MALOTES', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.19', nome: 'MATERIAL DE ESCRITORIO', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.20', nome: 'MANUT DE SOFTWARE', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.21', nome: 'CONTRIB/ANUIDADES', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.22', nome: 'TAXAS E EMOLUMENTO', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.23', nome: 'ENDOMARKETING', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.24', nome: 'IPTU ADM', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.25', nome: 'ISS RET FONTE', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.26', nome: 'CSRF S/ USO E CONSUMO 5952', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.27', nome: 'CARTAO DE CREDITO', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.28', nome: 'TAXAS DE ALVARAS', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.29', nome: 'CONFRATERNIZACOES', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.30', nome: 'MARCAS E PATENTES', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.31', nome: 'CUSTAS PROCESSUAIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.32', nome: 'ALUGUEL IMOVEIS ADM', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.33', nome: 'IRRF OUTROS SERVICOS 1708', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.34', nome: 'CONDUCOES ADMINISTRATIVA', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.35', nome: 'SERVICOS DE INVENTARIOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.36', nome: 'ALUGUEL MAQ E EQUIPAMENTOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.37', nome: 'ALUGUEL EQUIP INFORMATICA', nivel: 3, tipo: 'conta' },
          { codigo: '08.02.38', nome: 'MULTAS E TAXAS ADMINISTRATIVAS', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '08.03',
        nome: 'DESPESAS COM MANUTENCAO',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.03.01', nome: 'MANUTENCAO INSTALACOES', nivel: 3, tipo: 'conta' },
          { codigo: '08.03.02', nome: 'MANUTENCAO EDIFICACOES', nivel: 3, tipo: 'conta' },
          { codigo: '08.03.03', nome: 'MANUTENCAO EQP INFORMATICA', nivel: 3, tipo: 'conta' },
          { codigo: '08.03.04', nome: 'MANUTENCAO MAQ EQUIPAMENTO', nivel: 3, tipo: 'conta' },
          { codigo: '08.03.05', nome: 'MANUTENCAO AR CONDICIONADO', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '08.04',
        nome: 'DESPESAS COM PESSOAL ADMINISTRACAO E LOJAS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.04.01', nome: 'PREMIACOES FUNCIONARIOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.02', nome: 'ALIMENTACAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.03', nome: 'RESCISAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.04', nome: 'INSS', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.05', nome: 'CONTRIBUICAO SINDICAL', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.06', nome: 'EXAMES MEDICOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.07', nome: 'VALE TRANSPORTE', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.08', nome: 'ESTAGIOS E TREINAMENTOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.09', nome: 'VALE FUNCIONARIO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.10', nome: 'HORAS EXTRAS', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.11', nome: 'FARMACIA', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.12', nome: 'FARDAMENTO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.13', nome: 'EPI', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.14', nome: 'V. FUNC. PLANO ODONTOLOGICO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.15', nome: 'CESTAS BASICAS', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.16', nome: 'IRRF SOBRE SALARIO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.17', nome: 'GRATIFICACOES', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.18', nome: 'MULTA RESCISORIA', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.19', nome: 'ASSIST MEDICA', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.20', nome: 'RECRUT/SELECAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.21', nome: 'FGTS', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.22', nome: 'SALARIOS A PAGAR', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.23', nome: 'CO PARTICIPACAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.25', nome: 'VALE ALIMENTACAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.26', nome: 'ASSIST MEDICA FUNC ADM', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.27', nome: 'VALE COMBUSTIVEL', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.28', nome: '13º SAL ADM PROVISAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.29', nome: 'FERIAS ADM PROVISAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.30', nome: 'RETIRADA - SHENIA', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.31', nome: 'DESPESAS PESSOAL - ITEM 31', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.32', nome: 'DESPESAS PESSOAL - ITEM 32', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.34', nome: 'DESPESAS PESSOAL - ITEM 34', nivel: 3, tipo: 'conta' },
          { codigo: '08.04.38', nome: 'DESPESAS PESSOAL - ITEM 38', nivel: 3, tipo: 'conta' },
          ],
        },
      {
        codigo: '08.05',
        nome: 'DESPESAS COM MARKETING',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.05.01', nome: 'PROPAGANDAS EM MIDIAS TRADICIONAIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.05.02', nome: 'PROPAGANDAS EM MIDIAS DIGITAIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.05.03', nome: 'MERCHANDISING EM PONTO DE VENDAS', nivel: 3, tipo: 'conta' },
          { codigo: '08.05.04', nome: 'CONSULTORIAS E ASSESSORIAS DE MARKETING', nivel: 3, tipo: 'conta' },
          { codigo: '08.05.05', nome: 'MATERIAIS GRAFICOS PROMOCIONAIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.05.06', nome: 'ACOES DE RELACIONAMENTO COM CLIENTES', nivel: 3, tipo: 'conta' },
          { codigo: '08.05.07', nome: 'WORKSHOPS E EVENTOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.05.08', nome: 'CAMPANHAS E CONTEUDOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.05.09', nome: 'VOUCHERS INFLUENCERS', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '08.06',
        nome: 'DESPESAS COMERCIAIS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.06.01', nome: 'CAMPANHAS COMERCIAIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.06.02', nome: 'BRINDES', nivel: 3, tipo: 'conta' },
          { codigo: '08.06.04', nome: 'AJUDA DE CUSTO DE DESLOCAMENTO COMERCIAIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.06.05', nome: 'AJUDA DE CUSTO DE VIAGENS COMERCIAIS', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '08.07',
        nome: 'DESPESAS BANCARIAS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.07.01', nome: 'TARIFA DOC/TED', nivel: 3, tipo: 'conta' },
          { codigo: '08.07.02', nome: 'TARIFA MAN. TITULO VENCIDO', nivel: 3, tipo: 'conta' },
          { codigo: '08.07.03', nome: 'TARIFA NEGATIVACAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.07.04', nome: 'TARIFA MANUT DE CONTA', nivel: 3, tipo: 'conta' },
          { codigo: '08.07.05', nome: 'TARIFA PG DE SALARIO', nivel: 3, tipo: 'conta' },
          { codigo: '08.07.06', nome: 'TARIFAS DE BAIXAS DE TITULOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.07.07', nome: 'TARIFAS COM PRORROGACAO', nivel: 3, tipo: 'conta' },
          { codigo: '08.07.08', nome: 'TARIFAS DE COBRANCA', nivel: 3, tipo: 'conta' },
          { codigo: '08.07.09', nome: 'TARIFAS BANCARIAS', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '08.08',
        nome: 'DESPESAS COM DIRETORIA',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.08.01', nome: 'RETIRADA-THAIS', nivel: 3, tipo: 'conta' },
          { codigo: '08.08.02', nome: 'INSS SOBRE PROLABORE', nivel: 3, tipo: 'conta' },
          { codigo: '08.08.03', nome: 'IRRF SOBRE PROLABORE', nivel: 3, tipo: 'conta' },
          { codigo: '08.08.05', nome: 'RETIRADA - GERLANO', nivel: 3, tipo: 'conta' },
          { codigo: '08.08.06', nome: 'RETIRADA - CAIRO', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '08.09',
        nome: 'DESPESAS COM PERDAS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.09.01', nome: 'DOACAO DE PECAS SEM CONDICAO DE VENDA', nivel: 3, tipo: 'conta' },
          { codigo: '08.09.02', nome: 'FURTO DESCONHECIDO', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '08.11',
        nome: 'DESPESAS COM CREDITO E COBRANCA',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.11.01', nome: 'CONSULTA CADASTRAL', nivel: 3, tipo: 'conta' },
          { codigo: '08.11.02', nome: 'TARIFA DE REGISTRO DE TITULO', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '08.12',
        nome: 'DESPESAS COM VEICULOS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '08.12.01', nome: 'COMBUSTIVEL/LUBRIFICANTE', nivel: 3, tipo: 'conta' },
          { codigo: '08.12.02', nome: 'MANUTENCAO DE VEICULOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.12.03', nome: 'SEGURO VEICULOS', nivel: 3, tipo: 'conta' },
          { codigo: '08.12.04', nome: 'MULTAS DE TRANSITO', nivel: 3, tipo: 'conta' },
          { codigo: '08.12.05', nome: 'TX DETRAN/IPVA', nivel: 3, tipo: 'conta' },
          { codigo: '08.12.06', nome: 'ESTACIONAMENTO DE VEICULO', nivel: 3, tipo: 'conta' },
        ],
      },
    ],
  },
  {
    codigo: '10',
    nome: 'RESULTADOS COMPLEMENTARES',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      {
        codigo: '10.02',
        nome: 'RECEITAS NAO OPERACIONAIS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '10.02.01', nome: 'VENDAS DE BENS IMOBILIZADOS', nivel: 3, tipo: 'conta' },
          { codigo: '10.02.02', nome: 'VENDAS DE SUCATAS E RESIDUOS', nivel: 3, tipo: 'conta' },
          { codigo: '10.02.03', nome: 'PREMIOS E SEGUROS', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '10.01',
        nome: 'RECEITAS FINANCEIRAS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '10.01.01', nome: 'DESCONTOS FINANCEIROS OBTIDOS', nivel: 3, tipo: 'conta' },
          { codigo: '10.01.02', nome: 'MULTAS E JUROS AUFERIDOS', nivel: 3, tipo: 'conta' },
          { codigo: '10.01.03', nome: 'RENDIMENTOS DE APLICACOES', nivel: 3, tipo: 'conta' },
          { codigo: '10.01.04', nome: 'CREDITO INADIMPLENCIA', nivel: 3, tipo: 'conta' },
        ],
      },
      {
        codigo: '10.03',
        nome: 'DESPESAS FINANCEIRAS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '10.03.01', nome: 'MULTA/JUROS', nivel: 3, tipo: 'conta' },
          { codigo: '10.03.02', nome: 'IOF', nivel: 3, tipo: 'conta' },
          { codigo: '10.03.03', nome: 'TAC S/ EMPRESTIMO', nivel: 3, tipo: 'conta' },
          { codigo: '10.03.04', nome: 'JUROS S/EMPREST. E FINANCIAM.', nivel: 3, tipo: 'conta' },
          { codigo: '10.03.05', nome: 'JUROS S/ ANTECIPACAO', nivel: 3, tipo: 'conta' },
          { codigo: '10.03.06', nome: 'SEGURO SOBRE EMPRESTIMOS', nivel: 3, tipo: 'conta' },
          { codigo: '10.03.07', nome: 'DEBITO INADIMPLENCIA', nivel: 3, tipo: 'conta' },
          { codigo: '10.03.08', nome: 'TARIFAS COB CARTORIO', nivel: 3, tipo: 'conta' },
          { codigo: '10.03.09', nome: 'JUROS OPERACAO IMPORTACAO', nivel: 3, tipo: 'conta' },
        ],
      },
    ],
  },
  {
    codigo: '13',
    nome: 'DESPESAS TRIBUTARIAS',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      {
        codigo: '13.01',
        nome: 'DESPESAS SOBRE LUCRO',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '13.01.01', nome: 'CSLL PROVISAO', nivel: 3, tipo: 'conta' },
          { codigo: '13.01.02', nome: 'IRPJ PROVISAO', nivel: 3, tipo: 'conta' },
        ],
      },
    ],
  },
  {
    codigo: '17',
    nome: 'INVESTIMENTOS - IMOBILIZADOS',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      {
        codigo: '17.01',
        nome: 'BENS IMOBILIZADOS',
        nivel: 2,
        tipo: 'grupo',
        filhos: [
          { codigo: '17.01.01', nome: 'INV. COMPUTADORES E PERIFERICOS', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.02', nome: 'INV. TITULO DE CAPITALIZACAO', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.03', nome: 'INV. MAQUINAS E EQUIPAMENTOS', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.04', nome: 'INV. MOVEIS E UTENSILIOS', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.05', nome: 'INV. VEICULOS', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.06', nome: 'INV. REFORMAS E OBRAS', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.07', nome: 'INV. SOFTWARES', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.08', nome: 'INV. CSU - CESSAO DE DIREITOS', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.09', nome: 'INV. EXPANSAO - IMOVEIS IMOBILIZADO', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.10', nome: 'INV. IMOVEIS', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.11', nome: 'INV. EXPANSAO FABRICA', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.12', nome: 'INV. EXPANSAO FABRICA MURO', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.13', nome: 'INV. EXPANSAO FABRICA MURO 2', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.14', nome: 'CONSTRUCAO CASA GERLANO', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.15', nome: 'REFORMA FABRICA DISTRATO', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.16', nome: 'ADIANT. REFORMA FABRICA DISTRATO', nivel: 3, tipo: 'conta' },
          { codigo: '17.01.17', nome: 'INVESTIMENTOS CAIRO', nivel: 3, tipo: 'conta' },
        ],
      },
    ],
  },
  {
    codigo: '18',
    nome: 'AMORTIZACAO E DIVIDAS',
    nivel: 1,
    tipo: 'grupo',
    filhos: [
      { codigo: '18.02', nome: 'EMPRESTIMO PRINCIPAL', nivel: 2, tipo: 'conta' },
      { codigo: '18.03', nome: 'ICMS AUTO INFRACAO', nivel: 2, tipo: 'conta' },
      { codigo: '18.04', nome: 'EMPRESTIMO MUTUO', nivel: 2, tipo: 'conta' },
      { codigo: '18.05', nome: 'ICMS PARCELAMENTO', nivel: 2, tipo: 'conta' },
      { codigo: '18.06', nome: 'INSS AUTO INFRACAO CORPO SEXY', nivel: 2, tipo: 'conta' },
      { codigo: '18.07', nome: 'MULTA SEFAZ', nivel: 2, tipo: 'conta' },
    ],
  },
];
